// <auto-generated />
using LabasanCryptoFountain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LabasanCryptoFountain.Migrations
{
    [DbContext(typeof(LabasanCryptoFountainContext))]
    [Migration("20180403040601_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("LabasanCryptoFountain.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<decimal>("TotalSentDay");

                    b.Property<decimal>("TotalSentHour");

                    b.Property<decimal>("TotalSentMaslow1");

                    b.Property<decimal>("TotalSentMaslow2");

                    b.Property<decimal>("TotalSentMaslow3");

                    b.Property<decimal>("TotalSentMaslow4");

                    b.Property<decimal>("TotalSentMaslow5");

                    b.Property<decimal>("TotalSentMinute");

                    b.Property<decimal>("TotalSentMonth");

                    b.Property<decimal>("TotalSentSecond");

                    b.Property<decimal>("TotalSentWeek");

                    b.Property<decimal>("TotalSentXlm");

                    b.Property<decimal>("TotalSentYear");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("LabasanCryptoFountain.Models.Send", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.Property<DateTimeOffset>("SendEnd");

                    b.Property<DateTimeOffset>("SendStart");

                    b.Property<string>("Source");

                    b.Property<string>("TokenName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Send");
                });
#pragma warning restore 612, 618
        }
    }
}
