// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using TST_Fountain.Models;

namespace TST_Fountain.Migrations
{
    [DbContext(typeof(TST_FountainContext))]
    partial class TST_FountainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("TST_Fountain.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<decimal>("TotalSentDay");

                    b.Property<decimal>("TotalSentHour");

                    b.Property<decimal>("TotalSentMinute");

                    b.Property<decimal>("TotalSentMonth");

                    b.Property<decimal>("TotalSentSecond");

                    b.Property<decimal>("TotalSentWeek");

                    b.Property<decimal>("TotalSentYear");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("TST_Fountain.Models.Send", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<decimal>("Amount");

                    b.Property<string>("TokenName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Send");
                });
#pragma warning restore 612, 618
        }
    }
}
